Repository depromeet/praise-push-server, pull requests merged in 2024-01, with the labels that each got.

#46 :sparkles: feature: implement create comment
  src/main/java/com/praise/push/adapter/in/web/CommentController.java
  src/main/java/com/praise/push/adapter/in/web/KeywordController.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentJpaEntity.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentMapper.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentRepository.java
  src/main/java/com/praise/push/adapter/out/persistence/PostMapper.java
  src/main/java/com/praise/push/application/CommentService.java
  src/main/java/com/praise/push/application/port/in/CommentUseCase.java
  src/main/java/com/praise/push/application/port/in/CreateCommentCommand.java
  src/main/java/com/praise/push/application/port/in/dto/CommentDetailResponseDto.java
  src/main/java/com/praise/push/application/port/in/dto/CommentSimpleResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadCommentPort.java
  src/main/java/com/praise/push/application/port/out/RecordCommentPort.java
Labels: ✨ feature

#47 image upload interface
  build.gradle
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
  src/main/java/com/praise/push/application/PostService.java
  src/main/java/com/praise/push/application/port/in/CreatePostCommand.java
  src/main/java/com/praise/push/application/port/out/RecordImagePort.java
  src/main/java/com/praise/push/config/ObjectStorageConfig.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#53 Add Enum class
  src/main/java/com/praise/push/util/enums/Constants.java
Labels: ✨ feature

#56 :memo: docs : pull request 템플릿 추가(#55)
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 📚 docs

#66 🚑 hotfix: delete title argument
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostJpaEntity.java
  src/main/java/com/praise/push/adapter/out/persistence/PostMapper.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/application/PostService.java
  src/main/java/com/praise/push/application/port/in/CreatePostCommand.java
  src/main/java/com/praise/push/application/port/in/UpdatePostCommand.java
  src/main/java/com/praise/push/application/port/out/PostResponse.java
  src/main/java/com/praise/push/domain/Post.java
Labels: 🐞 fix, 🔨 refactor

#69 :recycle: refactor: modify domain and jpa entity (#61)
  src/main/java/com/praise/push/adapter/in/web/KeywordController.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentJpaEntity.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentMapper.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentRepository.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordJpaEntity.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordMapper.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordRepository.java
  src/main/java/com/praise/push/adapter/out/persistence/PostJpaEntity.java
  src/main/java/com/praise/push/adapter/out/persistence/PostMapper.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/application/CommentService.java
  src/main/java/com/praise/push/application/KeywordService.java
  src/main/java/com/praise/push/application/port/in/KeywordUseCase.java
  src/main/java/com/praise/push/application/port/in/dto/CommentDetailResponseDto.java
  src/main/java/com/praise/push/application/port/in/dto/CommentSimpleResponseDto.java
  src/main/java/com/praise/push/application/port/in/dto/KeywordResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadKeywordPort.java
  src/main/java/com/praise/push/domain/Comment.java
  src/main/java/com/praise/push/domain/Keyword.java
  src/main/java/com/praise/push/domain/Post.java
  src/main/resources/application.yml
  src/test/java/com/praise/push/application/KeywordServiceTest.java
Labels: 🔨 refactor

#79 Refactor Image upload
  src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
  src/main/java/com/praise/push/application/CommentService.java
  src/main/java/com/praise/push/application/PostService.java
  src/main/java/com/praise/push/application/port/out/RecordImagePort.java
  src/main/java/com/praise/push/util/enums/Names.java
Labels: ✨ feature, 🔨 refactor

#80 :recycle: refactor: refactoring comment pagination
  src/main/java/com/praise/push/adapter/in/web/CommentController.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/in/CommentUseCase.java
  src/main/java/com/praise/push/application/port/in/dto/CommentResponseDto.java
  src/main/java/com/praise/push/application/port/in/dto/CommentSimpleResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadCommentPort.java
  src/main/java/com/praise/push/application/service/CommentService.java
  src/main/java/com/praise/push/application/service/KeywordService.java
Labels: 🔨 refactor

#87 Fix file extension error
  src/main/java/com/praise/push/adapter/out/persistence/ImagePersistenceAdapter.java
Labels: ✨ feature, 🐞 fix

#89 :sparkles: add post scheduling
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/out/LoadPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/java/com/praise/push/batch/cron/post/jobs/PostBatchJob.java
  src/main/java/com/praise/push/batch/cron/post/scheduler/PostBatchScheduler.java
  src/main/java/com/praise/push/config/BatchConfig.java
  src/main/java/com/praise/push/domain/Post.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#90 🔧 config: update application.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ⚙️ config

#94 Refactor Post Crud
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/out/PostResponse.java
  src/main/java/com/praise/push/application/port/out/RecordPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/java/com/praise/push/domain/Post.java
  src/main/resources/application-local.yml
Labels: ✨ feature, 🔨 refactor

#91 :sparkles: feature: handle exception
  src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/CommentRepository.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/out/LoadCommentPort.java
  src/main/java/com/praise/push/application/service/CommentService.java
  src/main/java/com/praise/push/common/constant/Constants.java
  src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
  src/main/java/com/praise/push/common/error/exception/PraiseUpException.java
  src/main/java/com/praise/push/common/error/model/ErrorCode.java
Labels: ✨ feature

#97 ✨ Feature: Filter visible posts and invisible posts
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/in/dto/PostSummaryResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
Labels: ✨ feature, 🔨 refactor

#104 ✨ Feature: add userId parameter
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/out/LoadPostPort.java
  src/main/java/com/praise/push/application/port/out/LoadUserPort.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/java/com/praise/push/domain/Post.java
Labels: ✨ feature, 🔨 refactor

#99 :sparkles: feature: add validation of keyword and comments
  build.gradle
  src/main/java/com/praise/push/adapter/in/web/CommentController.java
  src/main/java/com/praise/push/adapter/in/web/KeywordController.java
  src/main/java/com/praise/push/application/port/in/CommentUseCase.java
  src/main/java/com/praise/push/application/port/in/CreateCommentCommand.java
  src/main/java/com/praise/push/application/port/in/ReadCommentsQuery.java
  src/main/java/com/praise/push/application/port/in/ReadKeywordsQuery.java
  src/main/java/com/praise/push/application/service/CommentService.java
  src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
  src/main/java/com/praise/push/common/error/model/ErrorCode.java
  src/main/java/com/praise/push/config/SwaggerConfig.java
Labels: ✨ feature

#102 :sparkles: feature: create user table index
  src/main/java/com/praise/push/domain/User.java
Labels: ✨ feature

#108 :sparkles: feature: add user entity field
  src/main/java/com/praise/push/application/port/out/LoginResponse.java
  src/main/java/com/praise/push/application/service/UserService.java
  src/main/java/com/praise/push/domain/User.java
Labels: ✨ feature

#111 :sparkles: feature: add random nickname
  src/main/java/com/praise/push/application/service/UserService.java
  src/main/java/com/praise/push/domain/User.java
Labels: ✨ feature

#116 🚑 Hotfix: Add userNickname
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/application/port/out/PostResponse.java
Labels: 🐞 fix

#122 Fix getPosts controller argument
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/in/dto/PostThumbnailResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
Labels: 🐞 fix

#117 ♻️ merge develop to main
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/in/dto/CommentResponseDto.java
  src/main/java/com/praise/push/application/port/in/dto/PostThumbnailResponseDto.java
  src/main/java/com/praise/push/application/port/out/LoadPostPort.java
  src/main/java/com/praise/push/application/port/out/PostResponse.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 👷‍♂️ chore

#123 🚑 Hotfix: add visible parameter
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
Labels: 🐞 fix

#125 🚑 Hotfix: refactor PostResponseDto(add postId)
  src/main/java/com/praise/push/adapter/in/web/PostController.java
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/in/PostUseCase.java
  src/main/java/com/praise/push/application/port/out/PostResponseDto.java
  src/main/java/com/praise/push/application/port/out/RecordPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/java/com/praise/push/common/model/ResponseDto.java
Labels: 🐞 fix

#130 :recycle: refactor: add asynchronous to error monitoring
  src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
  src/main/java/com/praise/push/common/error/model/ErrorEvent.java
  src/main/java/com/praise/push/common/error/model/ErrorEventListener.java
  src/main/java/com/praise/push/common/monitoring/MonitoringProvider.java
  src/main/java/com/praise/push/common/monitoring/SlackMonitoringProvider.java
  src/main/java/com/praise/push/config/AsyncConfig.java
Labels: ✨ feature, 🔨 refactor

#137 :recycle: refactor: refactoring random keyword recommendation
  src/main/java/com/praise/push/adapter/out/persistence/KeywordPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordRepository.java
  src/main/java/com/praise/push/application/port/out/RecordKeywordPort.java
  src/main/java/com/praise/push/application/service/KeywordService.java
  src/main/java/com/praise/push/batch/cron/post/jobs/KeywordBatchJob.java
  src/main/java/com/praise/push/batch/cron/post/scheduler/KeywordBatchScheduler.java
  src/main/java/com/praise/push/domain/Keyword.java
Labels: 🔨 refactor

#138 :twisted_rightwards_arrows: chore: merge develop into main
  src/main/java/com/praise/push/adapter/out/persistence/KeywordPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/KeywordRepository.java
  src/main/java/com/praise/push/application/port/out/RecordKeywordPort.java
  src/main/java/com/praise/push/application/service/KeywordService.java
  src/main/java/com/praise/push/batch/cron/post/jobs/KeywordBatchJob.java
  src/main/java/com/praise/push/batch/cron/post/scheduler/KeywordBatchScheduler.java
  src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
  src/main/java/com/praise/push/common/error/model/ErrorEvent.java
  src/main/java/com/praise/push/common/error/model/ErrorEventListener.java
  src/main/java/com/praise/push/common/monitoring/MonitoringProvider.java
  src/main/java/com/praise/push/common/monitoring/SlackMonitoringProvider.java
  src/main/java/com/praise/push/config/AsyncConfig.java
  src/main/java/com/praise/push/domain/Keyword.java
  src/test/java/com/praise/push/application/KeywordServiceTest.java
Labels: 👷‍♂️ chore

#141 ♻️ Refactor: post validation
  src/main/java/com/praise/push/adapter/in/web/PostController.java
Labels: 🔨 refactor

#139 :sparkles: feature: add health check controller
  src/main/java/com/praise/push/adapter/in/web/HealthController.java
Labels: ✨ feature

#148 :bug: fix: modify post visible open scheduler
  src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
  src/main/java/com/praise/push/application/port/out/RecordPostPort.java
  src/main/java/com/praise/push/application/service/PostService.java
Labels: 🐞 fix, 🔨 refactor

#153 Refactor invisible post order
  src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
Labels: 🐞 fix

#155 Feature post create limit
  src/main/java/com/praise/push/PraisePushApplication.java
  src/main/java/com/praise/push/adapter/in/web/UserController.java
  src/main/java/com/praise/push/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/praise/push/application/port/in/dto/UserPostStateResponseDto.java
  src/main/java/com/praise/push/application/port/out/RecordUserPort.java
  src/main/java/com/praise/push/application/service/PostService.java
  src/main/java/com/praise/push/application/service/UserService.java
  src/main/java/com/praise/push/domain/User.java
Labels: ✨ feature, 🐞 fix, 🔨 refactor

#157 :bug: fix: async monitoring error
  src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
  src/main/java/com/praise/push/common/error/model/ErrorEvent.java
  src/main/java/com/praise/push/common/error/model/ErrorRequest.java
  src/main/java/com/praise/push/common/monitoring/SlackMonitoringProvider.java
Labels: 🐞 fix
